### ISSUE TITLE
What's the plan to update riscv32-linux-nommu?

### ISSUE THREAD

**Issue by BabyMelvin** [regymm/quasiSoC#2]
I met the same case to need riscv32 linux nommu support. Currently, boot the riscv32 nommu kernel successfully, but the the ramfs's init process failed. I have tried to fix it, but not  success. So, What's the plan to update those patches, Thanks a lot firstly.

**Comment by regymm** [comment]
Hi, thanks for your interest in the project. 

Since it is 1) complicated, 2) unsupported by mainstream kernel, 3) condition changes over time, 4) I'm lazy, I haven't uploaded all the patches and tutorials yet... 
But I do have my modified code: 
My linux-5.9.4 repo contains necessary changes to the kernel(config files, flat binary loading hack, and uartlite driver modified to fit my own UART). In 5.9.4 the default flat binary loader has to be modified, but it seems it works out of the box in the latest kernels(see [this](https://github.com/damien-lemoal/buildroot/issues/2)). 

Also, what are you using to compile the init process? I modified the toolchain based on [this one](https://github.com/damien-lemoal/buildroot). The trick is you can compile elf2flt but then you have to use the 64-bit linking file(maybe with extra modification for 5.9.4 kernel). Also uclibc needs to be modified to compile(but no substantial change, I have a patch [here](https://mailman.openadk.org/mailman3/hyperkitty/list/devel@uclibc-ng.org/thread/UVU73HR552D6V24M6UKGKZQBGIHCNZOX/)). 

And are you using my riscv32 core or your self-written one? If mine, then I can share my pre-compiled kernel/initramfs if needed. If not, I'd recommend you to 1) compare the running result on your core and qemu, 2) write a very simple init to see if it runs. Because there can still be a ton of problems(especially with timer interrupts and syscalls) happening when you got kernel to run init but not further. 

Let's keep in touch.

**Comment by BabyMelvin** [comment]
So appreciated for your detail reply!

My compiler is **riscv32-unknown-linux-gnu** and  **busybox** for initramfs directly, modified elf2flt for support riscv32 .
These are my infos:

- Compile elf2flt by **riscv32-unknown-linux-gnu**  toolchain, which seems that elf2flt will update those ld etc of **riscv32-unknown-linux-gnu**. 
- When compile the init process(or helloworld like),  some elf's section's areas overlap. I tried to fix thoes overlap, but kernel still fail to start the init process.(That must be my fault modified).
- And i just test on qemu.(I am a software developer, not understand the FGPA etc 😭)
- Currently kernel seems boot success with riscv32 nommu, except that the init process failed.

```
[    0.384493] Freeing unused kernel memory: 624K
[    0.384713] This architecture does not have kernel memory protection.
[    0.385057] Run /init as init process
[    0.385201]   with arguments:
[    0.385323]     /init
[    0.385422]   with environment:
[    0.385544]     HOME=/
[    0.385641]     TERM=linux
[    0.391155] binfmt_flat: reference 0xfa1bdc to shared library 255, killing init!
[    0.392285] Failed to execute /init (error -8)
[    0.392460] Run /sbin/init as init process
[    0.392601]   with arguments:
[    0.392714]     /sbin/init
[    0.392814]   with environment:
[    0.392939]     HOME=/
[    0.393138]     TERM=linux
[    0.393534] Kernel panic - not syncing: Requested init /sbin/init failed (error -2).
[    0.394038] CPU: 0 PID: 1 Comm: init Not tainted 5.6.0-rc1 #78
[    0.394330] Call Trace:
[    0.394551] [<8009fa9c>] walk_stackframe+0x0/0x108
[    0.394761] [<8009fed8>] show_stack+0x3c/0x50
[    0.394920] [<806f4944>] dump_stack+0x8c/0xb8
[    0.395073] [<800a64a0>] panic+0x134/0x308
[    0.395219] [<807127dc>] kernel_init+0xb8/0x130
[    0.395376] [<8009e038>] ret_from_exception+0x0/0x18
[    0.396127] ---[ end Kernel panic - not syncing: Requested init /sbin/init failed (error -2). ]---
```

Thanks for your patches mentioned and professional advice. But some details i want to figure those out.
How did you compile [buildroot](https://github.com/damien-lemoal/buildroot)?  with `riscv32_nommu_defconfig` or `riscv64_nommu_defconfig`.I tried riscv32_nommu_defconfig met some compile erros. 
Could you please share your toolchain's info and compile methods at your spare time.
Thanks again for reply!

**Comment by regymm** [comment]
Looking at your kernel message, it seems you have some kind of "shared library" involved? Usually the init(busybox) is a statically linked flat binary and refers to no shared library. I'm not familiar with individual toolchain and elf2flt(that's exactly why I'm using buildroot), but it looks like your toolchain's problem. 

Also, seems you are using 5.6.0 kernel, I'm not sure this old kernel has essential riscv nommu updates yet. 

Anyway, I want to modify the buildroot and make it work out of the box for nommu rv32, but I haven't started it yet due to laziness. Maybe now it's time to do it. I'll also bump my kernel version to 5.18.14. It may take a week or two to pick up these old threads so please wait patiently. :smile:
